### ISSUE TITLE
Crash when server is shut down

### ISSUE THREAD

**Issue by bkircher** [gridscale/terraform-provider-gridscale#32]
### Terraform Version
$ terraform --version
Terraform v0.12.16
+ provider.gridscale v1.4.0

### Affected Resource(s)
- gridscale_server

### Traceback
```
panic: runtime error: invalid memory address or nil pointer dereference
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde04cb]
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: goroutine 98 [running]:
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/gridscale.(*listServersPowerStatus).shutdownServerSynchronously(0x1bca4a0, 0x12cdf00, 0xc0000be010, 0xc00000e678, 0xc0000ba4e0, 0x24, 0x0, 0x0)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/gridscale/common.go:107 +0x6b
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/gridscale.resourceGridscaleServerDelete(0xc000172bd0, 0x1072700, 0xc00000e678, 0x24, 0x1becb00)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/gridscale/resource_gridscale_server.go:603 +0xb8
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00015d080, 0xc000160640, 0xc000605260, 0x1072700, 0xc00000e678, 0x102f501, 0xc00062f8e8, 0x40c178)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:278 +0x4e7
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00015d580, 0xc00062fa68, 0xc000160640, 0xc000605260, 0x1becb00, 0x0, 0x0)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:289 +0x18f
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e4e8, 0x12cdf80, 0xc0003a4ae0, 0xc0002e03c0, 0xc00000e4e8, 0xc0003a4ae0, 0xc000177bd0)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x884
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10372c0, 0xc00000e4e8, 0x12cdf80, 0xc0003a4ae0, 0xc0002e0360, 0x0, 0x12cdf80, 0xc0003a4ae0, 0xc00019c580, 0x52a)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x23e
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c8000, 0x12d9200, 0xc00057ef00, 0xc00047a000, 0xc000153050, 0x1bc1680, 0x0, 0x0, 0x0)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc/server.go:995 +0x466
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0002c8000, 0x12d9200, 0xc00057ef00, 0xc00047a000, 0x0)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000156090, 0xc0002c8000, 0x12d9200, 0xc00057ef00, 0xc00047a000)
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc/server.go:710 +0x9f
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: created by github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-11-30T17:00:39.478+0100 [DEBUG] plugin.terraform-provider-gridscale_v1.4.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-gridscale/vendor/google.golang.org/grpc/server.go:708 +0xa1
2019-11-30T17:00:39.481+0100 [DEBUG] plugin: plugin process exited: path=/home/bk/gs/infra/dev/.terraform/plugins/linux_amd64/terraform-provider-gridscale_v1.4.0_x4 pid=202447 error="exit status 2"
2019/11/30 17:00:39 [DEBUG] gridscale_server.wolf-1: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2019/11/30 17:00:39 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/11/30 17:00:39 [TRACE] EvalWriteState: writing current state object for gridscale_server.wolf-1
2019/11/30 17:00:39 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/11/30 17:00:39 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2019/11/30 17:00:39 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/11/30 17:00:39 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: rpc error: code = Unavailable desc = transport is closing
2019/11/30 17:00:39 [TRACE] [walkDestroy] Exiting eval tree: gridscale_server.wolf-1 (destroy)
2019/11/30 17:00:39 [TRACE] vertex "gridscale_server.wolf-1 (destroy)": visit complete
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "gridscale_network.network-1 (destroy)" errored, so skipping
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "gridscale_storage.storage-1 (destroy)" errored, so skipping
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "gridscale_sshkey.bkircher (destroy)" errored, so skipping
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "provider.gridscale (close)" errored, so skipping
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/11/30 17:00:39 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/11/30 17:00:39 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2019/11/30 17:00:39 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 6
2019/11/30 17:00:39 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2019/11/30 17:00:39 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/11/30 17:00:39 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-11-30T17:00:39.493+0100 [DEBUG] plugin: plugin exited
2019-11-30T17:00:39.497+0100 [DEBUG] plugin: plugin process exited: path=/home/bk/gs/infra/dev/.terraform/plugins/linux_amd64/terraform-provider-gridscale_v1.4.0_x4 pid=202430
2019-11-30T17:00:39.498+0100 [DEBUG] plugin: plugin exited
```

**Comment by nvthongswansea** [comment]
This should be solved in https://github.com/terraform-providers/terraform-provider-gridscale/pull/33

**Comment by bkircher** [comment]
Yes, this is fixed by https://github.com/terraform-providers/terraform-provider-gridscale/issues/32. Awesome :clap:
